name: Bug report
about: Create a bug report to help us improve the game
title: "[BUG] simple and brief title"
labels: bug
assignees: ''
body:
- type: input
  id: description
  attributes:
    label: Describe the bug
    description: "A clear and concise description of what the bug is"
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Steps To Reproduce
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: input
  id: expected
  attributes:
    label: Expected Behavior
    description: "A clear and concise description of what you expected to happen"
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: "If applicable, add screenshots to help explain your problem"
  validations:
    required: false
- type: dropdown
  id: os
  attributes:
    label: Platform
    options:
      - linux
      - mac
      - windows
      - steam deck
    multiple: true
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Game Version
    options:
      - 1.0.0
  validations:
    required: true
- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    descriptions: "Add any other context about the problem here, such as which day you were on, whether characters were on the elevator or not, etc."
  validations:
    required: false
